FROM node:20

WORKDIR /app

COPY AdminSide ./AdminSide
COPY AdminSide/package*.json ./AdminSide/
COPY AdminSide/pm2.config.js ./AdminSide/
COPY ./Server/products.json ./Server/products.json

WORKDIR /app/AdminSide
RUN npm install

RUN npm install -g pm2

CMD ["pm2-runtime", "pm2.config.js"]