services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    ports:
      - "8080:8080"
      - "8081:8081"
    working_dir: /app/AdminSide
    volumes:
      - products-data:/app/Server

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    working_dir: /app/ClientSide
    volumes:
      - products-data:/app/Server

volumes:
  products-data: